# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_YFN7fVZq5jcpljSN9AJZYFkOI_oj4O
"""

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm.jfif')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm2.jfif')
cv2_imshow(rasm2)



oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)



from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm3.jfif')
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)



from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm4.jfif')
cv2_imshow(rasm)



oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)



from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('rasm5.jfif')
cv2_imshow(rasm)



oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)